<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<title>Cadastrar Leilões</title>
	<!-- Materialize CSS -->
	<link rel="stylesheet" href="css/materialize.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
	<!-- Navebar do Admin-->
	<nav class="brown darken-4">
    	<div class="nav-wrapper container">
    		<a href="casdastrar_leiloes.phtml" class="brand-logo">Cadastrar Leilões</a>
    		<ul id="nav-mobile" class="right hide-on-med-and-down">
    			<li><a href="indexadmin.php">Início</a></li>
				<li><a href="sistema_admin.php">Sistema</a></li>
				<li><a href="edita.php">Usuários</a></li>
				<li><a href="login/sair.php">Sair</a></li>
			</ul>
		</div>
	</nav>
	<br>
	<div class="row container">
		<form  method="post" class="col s12">
			<div class="row">
				<div class="input-field col s12 m12 l12">
					<input placeholder="Nome do Leilão" id="nome_leilao" type="text" name="form_name" class="validate">
					<label for="nome_leilao">Nome do Leilão</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s12 m12 l12">
					<input id="raca" name="form_raca" type="text" class="validate">
					<label for="raca">Raça</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s12 m12 l12">
					<input id="idade" name="form_idade" type="text" class="validate">
					<label for="idade">Idade</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s12 m12 l12">
					<input id="peso" name="form_peso" type="text" class="validate">
					<label for="peso">Peso</label>
				</div>
			</div>
			<div class="row">
				<div class="input-field col s12 m12 l12">
					<input id="valor" name="form_valor" type="text" class="validate">
					<label for="valor">Valor</label>
				</div>
			</div>
			<div class="row">
				<div class="col s12">
					<button class="btn brown darken-4 waves-effect waves-light" type="submit" value="Entrar">Cadastrar
					<i class="material-icons right">send</i>
  					</button>
				</div>
			</div>
		</form>
	</div>
	<!-- Jquery-->
    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <!-- Materialize JS -->
    <script src="js/materialize.js"></script
</body>
</html>