-- MySQL Script generated by MySQL Workbench
-- Mon Mar 27 18:54:31 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema webov2leilao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webov2leilao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webov2leilao` DEFAULT CHARACTER SET utf8 ;
USE `webov2leilao` ;

-- -----------------------------------------------------
-- Table `webov2leilao`.`leilao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webov2leilao`.`leilao` (
  `idleilao` INT NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `idade` VARCHAR(45) NOT NULL,
  `peso` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `valorkg` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idleilao`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
